# .github/workflows/fitbit-sync.yml
name: Fitbit Data Sync

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: false
        default: 'INFO'
        type: choice
        options:
          - DEBUG
          - INFO
          - WARNING
          - ERROR

permissions:
  id-token: write # Required for Workload Identity
  contents: read

env:
  GOOGLE_CLOUD_PROJECT: long-covid-8f42d

jobs:
  sync-fitbit-data:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Debug repository contents
      run: |
        echo "=== Repository Structure ==="
        ls -la
        echo ""
        echo "=== Python files ==="
        find . -name "*.py" -type f | head -10
        echo ""
        echo "=== Check for fitbit_sync.py ==="
        if [ -f "fitbit_sync.py" ]; then
          echo "✅ fitbit_sync.py found"
          ls -la fitbit_sync.py
        else
          echo "❌ fitbit_sync.py NOT found"
          echo "Available Python files:"
          find . -name "*.py" -type f
        fi
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin>=6.2.0 aiohttp>=3.8.0 python-dateutil>=2.8.0 python-dotenv>=1.0.0
        
    - name: Verify installations
      run: |
        python -c "import firebase_admin; print('✅ Firebase Admin SDK installed')"
        python -c "import aiohttp; print('✅ aiohttp installed')"
        python -c "import json; print('✅ json available')"

    # Option A: Workload Identity (Recommended)
    - id: 'auth'
      name: '🔐 Authenticate with Workload Identity'
      if: vars.USE_WORKLOAD_IDENTITY == 'true'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    # Option B: Service Account Key
    - name: '🔐 Authenticate with Service Account Key'
      if: vars.USE_WORKLOAD_IDENTITY != 'true'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY || secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

    - name: Test Firebase connection
      run: |
        python -c "
        import os, json, firebase_admin
        from firebase_admin import credentials, firestore
        try:
            print('🔍 Testing Firebase connection...')
            
            # Try different authentication methods
            cred = None
            auth_method = 'unknown'
            
            # Method 1: Workload Identity
            cred_path = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')
            if cred_path and os.path.exists(cred_path):
                print('🔑 Using Workload Identity credentials')
                cred = credentials.Certificate(cred_path)
                auth_method = 'workload_identity'
            
            # Method 2: Service Account Key (new format)
            elif os.environ.get('GOOGLE_SERVICE_ACCOUNT_KEY'):
                print('🔑 Using GOOGLE_SERVICE_ACCOUNT_KEY')
                service_account_info = json.loads(os.environ.get('GOOGLE_SERVICE_ACCOUNT_KEY'))
                cred = credentials.Certificate(service_account_info)
                auth_method = 'google_service_account_key'
            
            # Method 3: Legacy Firebase Service Account Key
            elif os.environ.get('FIREBASE_SERVICE_ACCOUNT_KEY'):
                print('🔑 Using legacy FIREBASE_SERVICE_ACCOUNT_KEY')
                service_account_info = json.loads(os.environ.get('FIREBASE_SERVICE_ACCOUNT_KEY'))
                cred = credentials.Certificate(service_account_info)
                auth_method = 'firebase_service_account_key'
            
            else:
                raise ValueError('No authentication credentials found')
            
            print(f'✅ Authentication method: {auth_method}')
            
            # Initialize Firebase with explicit project
            firebase_admin.initialize_app(cred, {
                'projectId': 'long-covid-8f42d'
            })
            db = firestore.client()
            
            # Test query
            users_ref = db.collection('users')
            test_query = users_ref.limit(1)
            docs = list(test_query.stream())
            print(f'✅ Firestore connected, test query returned {len(docs)} documents')
            
            # Check for Fitbit users
            fitbit_query = users_ref.where('selectedDevice', '==', 'fitbit').where('deviceConnected', '==', True)
            fitbit_users = list(fitbit_query.stream())
            print(f'✅ Found {len(fitbit_users)} Fitbit users ready for sync')
            
        except Exception as e:
            print(f'❌ Firebase connection failed: {e}')
            print('')
            print('🔍 Debug information:')
            print(f'GOOGLE_APPLICATION_CREDENTIALS: {\"✅\" if os.environ.get(\"GOOGLE_APPLICATION_CREDENTIALS\") else \"❌\"}')
            print(f'GOOGLE_SERVICE_ACCOUNT_KEY: {\"✅\" if os.environ.get(\"GOOGLE_SERVICE_ACCOUNT_KEY\") else \"❌\"}')
            print(f'FIREBASE_SERVICE_ACCOUNT_KEY: {\"✅\" if os.environ.get(\"FIREBASE_SERVICE_ACCOUNT_KEY\") else \"❌\"}')
            exit(1)
        "
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        
    - name: Run Fitbit sync
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        LOG_LEVEL: ${{ github.event.inputs.log_level || 'INFO' }}
      run: |
        echo "🚀 Starting Fitbit sync..."
        echo "Current directory: $(pwd)"
        echo "Python version: $(python --version)"
        echo "Project ID: long-covid-8f42d"
        echo "Checking fitbit_sync.py..."
        
        if [ ! -f "fitbit_sync.py" ]; then
          echo "❌ ERROR: fitbit_sync.py not found in repository"
          echo "Available files:"
          ls -la
          exit 1
        fi
        
        echo "✅ Running fitbit_sync.py..."
        python fitbit_sync.py
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 7

    - name: Notify on failure
      if: failure()
      run: |
        echo "::error::Fitbit sync failed at $(date)"
        echo "💡 Common solutions:"
        echo "1. Set up Workload Identity (recommended)"
        echo "2. Update GOOGLE_SERVICE_ACCOUNT_KEY secret"
        echo "3. Contact organization admin for access"

  # Health check job
  health-check:
    runs-on: ubuntu-latest
    needs: sync-fitbit-data
    if: always()
    
    steps:
    - name: Check sync health
      run: |
        echo "🔍 Checking sync job result: ${{ needs.sync-fitbit-data.result }}"
        
        if [ "${{ needs.sync-fitbit-data.result }}" == "success" ]; then
          echo "✅ Fitbit sync completed successfully"
          echo "::notice::Sync successful at $(date)"
        elif [ "${{ needs.sync-fitbit-data.result }}" == "failure" ]; then
          echo "❌ Fitbit sync failed"
          echo "::error::Sync failed at $(date)"
          echo ""
          echo "🔍 Common failure reasons:"
          echo "1. Authentication issues (organization policies)"
          echo "2. Missing or invalid credentials"
          echo "3. Firebase connection problems"
          echo "4. Project moved to organization - permissions changed"
          echo ""
          echo "📋 Next steps:"
          echo "1. Set up Workload Identity authentication"
          echo "2. Get new service account key from organization admin"
          echo "3. Check GitHub secrets are correctly set"
          exit 1
        else
          echo "⚠️ Sync result: ${{ needs.sync-fitbit-data.result }}"
          exit 1
        fi
        
    - name: Post-sync summary
      if: needs.sync-fitbit-data.result == 'success'
      run: |
        echo "📊 Sync Summary:"
        echo "- Project: long-covid-8f42d"
        echo "- Workflow: ${{ github.workflow }}"
        echo "- Run number: ${{ github.run_number }}"
        echo "- Triggered by: ${{ github.event_name }}"
        echo "- Timestamp: $(date -u)"
